production:

  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  encoding: unicode 
  database: numerology_development
  pool: 5
  username: codio
  password: 
  host: localhost
  template: template0
    
test:
  adapter: postgresql
  encoding: unicode 
  database: numerology_test
  pool: 5
  username: codio
  password: 
  host: localhost
  template: template0